name: CI
on:
  push:
    branches:
    - master220
    - whitelist220
    - testmerge
    - dev
  pull_request:
    branches:
    - master220
    - whitelist220
  merge_group:
  workflow_call:

jobs:
  run_linters:
    name: Run Linters
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: $HOME/SpacemanDMM
          key: ${{ runner.os }}-spacemandmm
      - name: Install Tools
        run: |
          bash tools/ci/install_build_deps.sh
          bash tools/ci/install_dreamchecker.sh
      - name: Run Linters
        run: |
          find . -name "*.json" -not -path "*/node_modules/*" -print0 | xargs -0 python3 ./tools/ci/json_verifier.py
          tools/ci/build_tgui.sh
          tools/ci/check_grep.sh
          python3 tools/ci/check_line_endings.py
          python3 tools/ci/unticked_files.py ${GITHUB_WORKSPACE}
      - name: Run DreamChecker
        shell: bash
        run: ~/dreamchecker 2>&1 | bash tools/ci/annotate_dm.sh

  compile_all_maps:
    name: Compile All Maps
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: $HOME/BYOND
          key: ${{ runner.os }}-byond
      - name: Compile All Maps
        run: |
          tools/ci/install_byond.sh
          source $HOME/BYOND/byond/bin/byondsetup
          tools/ci/generate_maplist.sh
          tools/ci/dm.sh -Mci_map_testing paradise.dme

  unit_tests_and_sql:
    name: Unit Tests + SQL Validation
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false # Let all map tests run to completion
      matrix:
        maptype: ['/datum/map/cyberiad', '/datum/map/delta', '/datum/map/cerestation']
        byondtype: ['STABLE']
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd "mariadb-admin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: $HOME/BYOND
          key: ${{ runner.os }}-byond
      - name: Setup & Validate DB
        run: |
          sudo systemctl start mysql
          python3 tools/ci/generate_sql_scripts.py
          tools/ci/validate_sql.sh
      - name: Install RUST_G Deps
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update || true
          sudo apt install libgcc-s1:i386
          bash tools/ci/install_rustg.sh
      - name: Install DMJIT
        run: |
          sudo apt install libncurses6:i386
          bash tools/ci/install_dmjit.sh
      - name: Compile & Run Unit Tests
        run: |
          tools/ci/install_byond.sh '${{ matrix.byondtype }}'
          source $HOME/BYOND/byond/bin/byondsetup
          tools/ci/dm.sh -DCIBUILDING paradise.dme
          echo '${{ matrix.maptype }}' > data/next_map.txt
          tools/ci/run_server.sh

